// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALBlBTWAlFem7ygEPi0ma9BrsDn3NROvU',
    appId: '1:261899636651:web:bab64687d269f329cd4cee',
    messagingSenderId: '261899636651',
    projectId: 'latihan-beee7',
    authDomain: 'latihan-beee7.firebaseapp.com',
    storageBucket: 'latihan-beee7.appspot.com',
    measurementId: 'G-CMFG1TNMZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYt1zznxgMTzCi9V9-FrQmab8RxPzi_S0',
    appId: '1:261899636651:android:98fa5c7fe4d3d8a9cd4cee',
    messagingSenderId: '261899636651',
    projectId: 'latihan-beee7',
    storageBucket: 'latihan-beee7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ghQqmSs24mzvE-3kxztFEJV046fDcXs',
    appId: '1:261899636651:ios:6821b3c5561a635ecd4cee',
    messagingSenderId: '261899636651',
    projectId: 'latihan-beee7',
    storageBucket: 'latihan-beee7.appspot.com',
    iosClientId: '261899636651-3m6bhh5mmfp7pe7ggglnl0u2cfciu964.apps.googleusercontent.com',
    iosBundleId: 'com.example.latihan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0ghQqmSs24mzvE-3kxztFEJV046fDcXs',
    appId: '1:261899636651:ios:cd9bda3b2c11966ecd4cee',
    messagingSenderId: '261899636651',
    projectId: 'latihan-beee7',
    storageBucket: 'latihan-beee7.appspot.com',
    iosClientId: '261899636651-f62ipl3sspfa6nap7tbnt0io1maq05qs.apps.googleusercontent.com',
    iosBundleId: 'com.example.latihan.RunnerTests',
  );
}
